### ISSUE TITLE
create spec file failing with stack trace

### ISSUE THREAD

**Issue by tomPorter** [astrauka/TestRSpec#11]
OSX El capitan
python 2.7 via continuum anaconda install
SublimeText 3 Build 3114

I had a project open with a class file called `game.rb` open in single buffer, then ran the create spec command.  Not sure if I am doing this right!

``` python
TestRSpec: Creating sepc file
Traceback (most recent call last):
  File "/Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 36, in __call__
KeyError: (<function CreateSpecFile._file_name at 0x1097f33b0>, (), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "test_rspec in /Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package", line 80, in run
  File "/Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/create_spec_file.py", line 15, in run
  File "/Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/create_spec_file.py", line 20, in _create_directories
  File "/Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 38, in __call__
  File "/Users/tporter/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/create_spec_file.py", line 42, in _file_name
  File "./python3.3/posixpath.py", line 83, in join
TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str'
```

I then opened a second buffer and saved the empty file as  `game_spec.rb` and with focus on that window, ran the create spec command again which showed `TestRSpec: Creating sepc file` but no other signs of activity.

**Comment by tomPorter** [comment]
Error between keyboard and monitor!

I needed to have a spec subdir in my project directory, and all worked well.
