### ISSUE TITLE
TestRspec not running

### ISSUE THREAD

**Issue by argentum47** [astrauka/TestRSpec#18]
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "test_rspec in /Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package", line 50, in run
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 12, in current
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 20, in _validate_can_run_spec
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 44, in _notify_missing_project_root
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/task_context.py", line 73, in log
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 17, in log
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 38, in __call__
  File "/Users/amitava/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 22, in panel
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by astrauka** [comment]
Have you tried restarting Sublime?

**Comment by argentum47** [comment]
Yes, many a time. The problem persists

**Comment by astrauka** [comment]
The root cause is missing project root. The plugin could not determine that
https://github.com/astrauka/TestRSpec/blob/2cccf2653de0703dce9267b97beb7894f76f3810/rspec/execute_spec.py#L20

This is where the root is determined https://github.com/astrauka/TestRSpec/blob/2cccf2653de0703dce9267b97beb7894f76f3810/rspec/project_root.py

Is your spec that you are running held in `spec/` directory?

@OlegSmelov could you check why missing project root logging fails?

**Comment by argentum47** [comment]
yeah yeah .. I have the spec in spec directory, its an usual ruby rails project

**Comment by astrauka** [comment]
@argentum47 have you found out what was the problem?
