### ISSUE TITLE
Exceptions when trying to use plugin

### ISSUE THREAD

**Issue by TheSmartnik** [astrauka/TestRSpec#25]
Hi, thanks for the plugin. It is really really helpful. I've been using it for quite awhile on my old system, however recently I installed plugin on my new laptop and it doesn't work. None of the features.

Config is default, as well as rails project

Here is the traceback
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 818, in run_
    return self.run(edit)
  File "test_rspec in /Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package", line 56, in run
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 12, in current
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 20, in _validate_can_run_spec
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 44, in _notify_missing_project_root
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/task_context.py", line 73, in log
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 17, in log
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 38, in __call__
  File "/Users/user/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 22, in panel
AttributeError: 'NoneType' object has no attribute 'items'
```

**Comment by astrauka** [comment]
@TheSmartnik do you still experience the issue?
Sadly I am not maintaining the plugin anymore, so can only guide you if you want to find out the issue and propose a fix

**Comment by meetme2meat** [comment]
I'm facing this issue.

**Comment by TheSmartnik** [comment]
@astrauka yeah, i'm still experience the issue. I'll try to fix it and send pr till the end of the week. I don't really know python, but I'll try to figure something out

**Comment by TheSmartnik** [comment]
@astrauka @meetme2meat Sorry for a long reply.
The issue was rather stupid, to be honest. I just hadn't restarted sublime 🤦‍♂️

Sorry for trouble

**Comment by astrauka** [comment]
Restarting Sublime is one of the most common fixes...
