### ISSUE TITLE
Plugin modules reload fails on plugin version update

### ISSUE THREAD

**Issue by astrauka** [astrauka/TestRSpec#4]
```
reloading plugin TestRSpec.test_rspec
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 696, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "test_rspec in /Users/gediminasz/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package", line 13, in <module>
  File "./imp.py", line 276, in reload
zipimport.ZipImportError: bad local file header in /Users/gediminasz/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package
```

Add hooks to clean imp loaded modules

**Comment by astrauka** [comment]
No proper fix as per https://forum.sublimetext.com/t/hot-update-without-restarting-sublime/14965/3

Will add "Please restart Sublime Text if plugin stopped working" to avoid issues on upgrade
