### ISSUE TITLE
ImportError: No module named 'rspec.last_copy'

### ISSUE THREAD

**Issue by lewispb** [astrauka/TestRSpec#47]
```reloading plugin TestRSpec.test_rspec
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 125, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1199, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/test_rspec.py", line 11, in <module>
ImportError: No module named 'rspec.last_copy'
```

**Comment by OlegSmelov** [comment]
Does it happen after a restart?

**Comment by lewispb** [comment]
No, I just restarted and it works fine, thank you!

**Comment by OlegSmelov** [comment]
I think this should now be fixed by a combination of https://github.com/astrauka/TestRSpec/commit/f519c46f5668db7c1d4a4f1db8aff89c083c9161 and https://github.com/astrauka/TestRSpec/commit/deff3d5892582b28943ef8be2b0701d61be9ea39.
