### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'items' when running any command

### ISSUE THREAD

**Issue by Startouf** [astrauka/TestRSpec#49]
The following error occurs when running any command

```
TestRSpec: Running rspec
Traceback (most recent call last):
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 43, in __call__
KeyError: (<function Output.panel at 0x7f815140f0e0>, (), frozenset())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1088, in run_
    return self.run(edit)
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/test_rspec.py", line 26, in run
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 14, in current
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 23, in _validate_can_run_spec
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/execute_spec.py", line 49, in _notify_missing_project_root
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/task_context.py", line 73, in log
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 18, in log
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/plugin_helpers/utils.py", line 45, in __call__
  File "/Users/me/Library/Application Support/Sublime Text 3/Installed Packages/TestRSpec.sublime-package/rspec/output.py", line 23, in panel
AttributeError: 'NoneType' object has no attribute 'items'
```

Latest version of the plugin available on github at the time of writing
macOS 11.2.3
Sublime 3.2.2 build 3211

**Comment by OlegSmelov** [comment]
Please attach your `TestRSpec.sublime-settings` file. Looking at the stack trace, something's wrong with `panel_settings` key in your settings.

**Comment by Startouf** [comment]
Hello, my `TestRSpec.sublime-settings` is empty, and the defaults of my `Preferences.sublime-settings` on macOS are

```
{
  "panel_settings": {
    "encoding": "utf-8",
    "syntax": "Packages/TestRSpec/themes/TestConsole.tmLanguage",
    "color_scheme": "Packages/TestRSpec/themes/TestConsole.hidden-tmTheme",
  },
  ```

![Screenshot 2021-05-03 at 20 22 56](https://user-images.githubusercontent.com/7388889/116916258-601e7480-ac4d-11eb-9fc1-f39b0e308a7b.png)

**Comment by OlegSmelov** [comment]
It looks like TestRSpec settings file isn't even present. I still suspect something's wrong with the settings, but I have no idea what it is, I've never seen this issue before.

Can you run this in Sublime console (<kbd>Ctrl</kbd> + <kbd>`</kbd>)? Paste one line at a time.

```python
import sublime

print(sublime.load_settings("Preferences.sublime-settings").get("panel_settings"))
print(sublime.load_settings("TestRSpec.sublime-settings").get("panel_settings"))
print(view.settings().get("panel_settings"))
```

**Comment by Startouf** [comment]
Here is the output

```
>>> print(sublime.load_settings("Preferences.sublime-settings").get("panel_settings"))
{'color_scheme': 'Packages/TestRSpec/themes/TestConsole.hidden-tmTheme', 'syntax': 'Packages/TestRSpec/themes/TestConsole.tmLanguage', 'encoding': 'utf-8'}
>>> print(sublime.load_settings("TestRSpec.sublime-settings").get("panel_settings"))
None
>>> print(view.settings().get("panel_settings"))
{'color_scheme': 'Packages/TestRSpec/themes/TestConsole.hidden-tmTheme', 'syntax': 'Packages/TestRSpec/themes/TestConsole.tmLanguage', 'encoding': 'utf-8'}

```

**Comment by OlegSmelov** [comment]
The output looks normal. And yet, whenever the plugin tries to load `panel_settings`, it somehow gets `None`. 🤔

I'm shooting in the dark here, but can you try a fix from a branch (https://github.com/astrauka/TestRSpec/tree/fix/simplify_settings)?

```sh
# first, remove TestRSpec package with Package Control, then:

cd ~/Library/Application\ Support/Sublime\ Text\ 3/Packages

git clone https://github.com/astrauka/TestRSpec.git

cd TestRSpec
git checkout fix/simplify_settings
```

**Comment by Startouf** [comment]
Oh my... sorry after trying your solution and seeing it still did not work, I thought the problem must be coming from somewhere else, and I realized I was trying to apply some TestRspec actions to some file that was not even in my workspace / persisted yet =_=

Sorry for the trouble, your extension is actually working fine, and works even with controller specs in /request folder, holy grail !

**Comment by OlegSmelov** [comment]
No problem! 😄 But I still don't understand why the plugin crashes, ideally it wouldn't crash even with files outside of current working directory...
